name: Build Scrutiny App (Windows)

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Check-out repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          architecture: 'x64' 

      # Fetch all the build dependencies
      - name: Install dependencies
        run: pip install -e .[build]

      # Launch Nuitka
      - name: Nuitka build
        run: bash -c "./scripts/nuitka_build.sh"
      
      # Launch InnoSetup
      - name: InnoSetup packaging
        run: bash -c "./scripts/make_windows_installer.sh"
