name: Build Scrutiny App

on:
  workflow_dispatch :
  push:
    tags:
        - 'v*'

jobs:
  build-user-guide:
    runs-on: ubuntu-22.04
    steps:
      # Check-out repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Fetch all the build dependencies
      - name: Install dependencies
        run: pip install -e .[build]

      - name: Install Latex tools
        run: sudo apt-get update && sudo apt-get install -y latexmk texlive-latex-base  texlive-latex-extra texlive-latex-recommended
        shell: bash

      - name: User guide
        run: ./scripts/build_userguide.sh
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: User Guide ${{ github.ref_name }}
          path: ./docs/user_guide/build/latex/*.pdf
