name: Build Scrutiny App (Mac OS)

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Check-out repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          architecture: 'x64' 

      # Fetch all the build dependencies
      - name: Install dependencies
        run: pip install -e .[build]

      # Launch Nuitka
      - name: Nuitka build
        run: ./scripts/nuitka_build.sh
        shell: bash

      # Create a DMG file
      - name: Create package
        run: ./scripts/make_macos_dmg.sh
        shell: bash

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Mac OS app
          path: ./nuitka_build/installer/*.dmg
