name: Build Scrutiny App (Windows)

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          architecture: 'x64' 

      - name: test
        run: bash -c "echo test"
      
