name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print the purpose of run
        run: echo  ${{ inputs.tags }} purpose    
